### ISSUE TITLE
ttl issues

### ISSUE THREAD

**Issue by JamesKyburz** [rvagg/node-generic-session#2]
I was investigating why my sessions where timing out after 20 minutes when using the default 2 week expiry.....

The issue is with the expiry units.

The seconds expiry set by generic-session is passed to level-session and level-ttl.

The cookie expiry is correct but the ttl in leveldb is only 20 minutes.

Not sure if this is an issue for generic-session or level-session?

**Comment by JamesKyburz** [comment]
I noticed this issue when using level-session

level-ttl and lru-cache use ms a expiry units and this module expects seconds.

The cookie expiry is [set correctly](https://github.com/rvagg/node-generic-session/blob/master/lib/index.js#L37) however the expiry is sent to lru-cache/level-ttl [as seconds](https://github.com/rvagg/node-generic-session/blob/master/lib/index.js#L92)

The tests only verify the cookie is correct when the ttl will expire before the cookie does.

I suppose what I'm wondering is can we change this module to use ms instead?

If no I can just close. It's not a big deal because of the expiry if the cookie expiry is greater than the session expiry (when using level-session) the session still expires ;)

**Comment by rvagg** [comment]
I think I'd prefer to leave it as seconds because it maps directly to the way cookies work and changing it, even with a major version bump, might result in some awkward unintended consequences. Would you mind putting in a pull request to fix the passing of seconds to the downstream modules that should be getting milliseconds?

**Comment by JamesKyburz** [comment]
I agree leaving the seconds option as is.

Now the get/set methods are passed to the store as milliseconds.

The tests passed, but I didn't write any new ones... (I noticed for example the memory store had a 2 week expiry and ignore the expiry option sent in set/get)

Let me know what you think.


Thanks.
